<a href="https://colab.research.google.com/github/MazurovaNN/neural-network/blob/main/lesson5_dz5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re

In [3]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [4]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [5]:
len(text)

205

In [6]:
num_characters = 34 #33 буквы + пробел

In [7]:
import keras
from keras.preprocessing.text import Tokenizer

In [8]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [9]:
tokenizer.fit_on_texts(text)

In [10]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [11]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [12]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

199

In [14]:
import numpy as np

In [15]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [16]:
len(X)

199

In [17]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [18]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
from keras.layers import *
from keras.models import Sequential

In [20]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 500)               267500    
                                                                 
 dense (Dense)               (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 15ms/step - loss: 3.4065 - accuracy: 0.0603
Epoch 2/100
7/7 [==============================] - 0s 15ms/step - loss: 2.4539 - accuracy: 0.3116
Epoch 3/100
7/7 [==============================] - 0s 14ms/step - loss: 1.9974 - accuracy: 0.4271
Epoch 4/100
7/7 [==============================] - 0s 15ms/step - loss: 1.5312 - accuracy: 0.6131
Epoch 5/100
7/7 [==============================] - 0s 15ms/step - loss: 1.2990 - accuracy: 0.5678
Epoch 6/100
7/7 [==============================] - 0s 15ms/step - loss: 1.0440 - accuracy: 0.6482
Epoch 7/100
7/7 [==============================] - 0s 15ms/step - loss: 0.8782 - accuracy: 0.7387
Epoch 8/100
7/7 [==============================] - 0s 15ms/step - loss: 0.7814 - accuracy: 0.8141
Epoch 9/100
7/7 [==============================] - 0s 22ms/step - loss: 0.7560 - accuracy: 0.7789
Epoch 10/100
7/7 [==============================] - 0s 24ms/step - loss: 0.6273 - accuracy: 0.8492
Epoch 11/100
7/7 [=

In [22]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [23]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 20ms/step
утренноитввд на гяоблопт коньи п доттьга с отлтчных резу


СЛОВА

In [53]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '') # убираем первый невидимый символ

In [54]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts([texts])

In [55]:
print(tokenizer.word_index)

{'вы': 1, 'в': 2, 'понедельник': 3, 'лучший': 4, 'ответ': 5, 'на': 6, 'проблемы': 7, 'которые': 8, 'возникли': 9, 'думайте': 10, 'позитивно': 11, 'и': 12, 'верьте': 13, 'свою': 14, 'способность': 15, 'достигать': 16, 'отличных': 17, 'результатов': 18, 'если': 19, 'смогли': 20, 'подняться': 21, 'с': 22, 'постели': 23, 'значит': 24, 'супер': 25, 'герой': 26}


In [56]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('вы', 3), ('лучший', 1), ('ответ', 1), ('на', 1), ('проблемы', 1), ('которые', 1), ('возникли', 1), ('в', 3), ('понедельник', 2), ('думайте', 1)]


In [57]:
data = tokenizer.texts_to_sequences([texts])

In [58]:
data

[[1,
  4,
  5,
  6,
  7,
  8,
  9,
  2,
  3,
  10,
  11,
  12,
  13,
  2,
  14,
  15,
  16,
  17,
  18,
  19,
  1,
  20,
  2,
  3,
  21,
  22,
  23,
  24,
  1,
  25,
  26]]

In [59]:
len (data[0])

31

In [60]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print( res.shape )

(31, 1000)


In [61]:
inp_words = 3
n = res.shape[0]-inp_words

In [62]:
X = np.array([res[i:i+inp_words, :] for i in range(n)])
Y = res[inp_words:]


In [63]:
model = Sequential()
model.add(Input((inp_words, maxWordsCount)))
model.add(SimpleRNN(128, activation='tanh'))
model.add(Dense(maxWordsCount, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 128)               144512    
                                                                 
 dense_2 (Dense)             (None, 1000)              129000    
                                                                 
Total params: 273512 (1.04 MB)
Trainable params: 273512 (1.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [64]:
history = model.fit(X, Y, batch_size=32, epochs=13)

Epoch 1/13
1/1 [==============================] - 1s 1s/step - loss: 6.9082 - accuracy: 0.0000e+00
Epoch 2/13
1/1 [==============================] - 0s 18ms/step - loss: 6.8823 - accuracy: 0.0000e+00
Epoch 3/13
1/1 [==============================] - 0s 17ms/step - loss: 6.8560 - accuracy: 0.0000e+00
Epoch 4/13
1/1 [==============================] - 0s 18ms/step - loss: 6.8292 - accuracy: 0.0357
Epoch 5/13
1/1 [==============================] - 0s 19ms/step - loss: 6.8015 - accuracy: 0.3929
Epoch 6/13
1/1 [==============================] - 0s 18ms/step - loss: 6.7726 - accuracy: 0.6071
Epoch 7/13
1/1 [==============================] - 0s 16ms/step - loss: 6.7423 - accuracy: 0.8571
Epoch 8/13
1/1 [==============================] - 0s 20ms/step - loss: 6.7102 - accuracy: 0.9286
Epoch 9/13
1/1 [==============================] - 0s 16ms/step - loss: 6.6759 - accuracy: 0.9286
Epoch 10/13
1/1 [==============================] - 0s 15ms/step - loss: 6.6389 - accuracy: 0.9286
Epoch 11/13
1/1 [==

In [65]:
def buildPhrase(texts, str_len = 20):
  res = texts
  data = tokenizer.texts_to_sequences([texts])[0]
  for i in range(str_len):
    x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
    inp = x.reshape(1, inp_words, maxWordsCount)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    indx = pred.argmax(axis=1)[0]
    data.append(indx)

    res += " " + tokenizer.index_word[indx] # дописываем строку

  return res

In [67]:
res = buildPhrase("лучший ответ на проблемы")
print(res)

1/1 [==============================] - 0s 41ms/step
лучший ответ на проблемы проблемы которые возникли возникли в понедельник понедельник думайте позитивно постели и верьте в супер свою способность позитивно смогли отличных понедельник


In [68]:
res = buildPhrase("вы в понедельник")
print(res)

1/1 [==============================] - 0s 34ms/step
вы в понедельник понедельник позитивно и и в свою способность достигать отличных результатов если вы смогли в понедельник подняться с постели значит вы


In [69]:
res = buildPhrase("если вы смогли")
print(res)

1/1 [==============================] - 0s 22ms/step
если вы смогли в понедельник подняться с постели значит вы супер герой на подняться которые возникли в понедельник думайте позитивно и верьте в


In [70]:
res = buildPhrase("верьте в свою способность")
print(res)

1/1 [==============================] - 0s 24ms/step
верьте в свою способность способность достигать отличных отличных результатов если вы вы смогли в понедельник понедельник подняться позитивно с постели герой в вы понедельник
